# Generated by Django 5.1.2 on 2024-11-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='Task Title'),
        ),
    ]
