# Generated by Django 5.0.7 on 2025-07-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_my_date_task_priority_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='my_date',
            new_name='due_date',
        ),
    ]
